# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='robot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stack',
            name='users',
            field=models.ManyToManyField(to='online.User'),
        ),
    ]
