# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-06 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister_assign_app', '0003_delete_usermanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
