# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister_assign_app', '0004_auto_20180206_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='hashpw',
        ),
    ]
