# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-11 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoninja_app', '0002_auto_20171011_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='users',
            field=models.ManyToManyField(to='dojoninja_app.Ninja'),
        ),
        migrations.AddField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(to='dojoninja_app.Ninja'),
        ),
    ]
